.env.example
.github/workflows/ci.yml
.gitignore
README.md
package-lock.json
package.json
scripts/dbSetup.ts
src/db/Connection.ts
src/index.ts
tsconfig.build.json
tsconfig.json

* Add singleton class for mongo connections that can be re-used across the app
* Add scripts for `npm run db:setup`, `npm run db:delete`, and `npm run db:reset` similar to deqm-test-server, but they only deal with collections for Measure, Library, and MeasureReport
Example usage of the database connection can be seen in the scripts. Test them out, run the server, etc.

Add mongo utilities with collection script

---

package.json
scripts/dbSetup.ts
src/config/serverConfig.ts
src/services/LibraryService.ts
src/services/MeasureService.ts
src/util/bundleUtils.ts
src/util/validationUtils.ts
test/services/LibraryService.test.ts
test/services/MeasureService.test.ts
test/util/bundleUtils.test.ts
test/util/validationUtils.test.ts

Creates the `/4_0_1/Measure/$package` endpoint which bundles a Measure with all its Libraries and dependent Libraries recursively, as outlined in the [docs](https://build.fhir.org/ig/HL7/cqf-measures/OperationDefinition-Measure-package.html )
- 4 new endpoints:
- `GET 4_0_1/Measure/$package`
- `GET 4_0_1/Measure/<id>/$package`
- `POST 4_0_1/Measure/$package`
- `POST 4_0_1/Measure/<id>/$package`
- Wowza new `db:loadBundle` script!
- Added new endpoints in `serverConfig`
- Created `db:loadBundle` script
- lots n' lots of testing
- `npm run check`
- `git clone https://github.com/cqframework/ecqm-content-r4-2021.git`
- `npm run db:reset`
- ```npm run db:loadBundle "ecqm-content-r4-2021/bundles/measure/ColorectalCancerScreeningsFHIR/ColorectalCancerScreeningsFHIR-bundle.json"```
- `npm start` …

Measure $package

---

src/config/serverConfig.ts
src/services/LibraryService.ts
src/services/MeasureService.ts
src/util/bundleUtils.ts
src/util/queryUtils.ts
test/services/LibraryService.test.ts
test/services/MeasureService.test.ts
test/util/bundleUtils.test.ts

Creates the `/4_0_1/Library/$package` endpoint which bundles a Library with all of its dependent libraries recursively, as outlined in the [docs](https://build.fhir.org/ig/HL7/cqf-measures/OperationDefinition-Library-package.html).
- 4 new endpoints:
- `GET 4_0_1/Library/$package`
- `GET 4_0_1/Library/<id>/$package`
- `POST 4_0_1/Library/$package`
- `POST 4_0_1/Library/<id>/$package`
- Additional testing for these endpoints as well as some for Measure/$package
- `src/config/serverConfig.ts` - added above endpoints
- `src/services/LibraryService.ts` - added `package` function which handles the above endpoints. It is similar to the `package` function in `MeasureService.ts`.
- `src/util/bundleUtils` - created a `createLibraryPackageBundle` function and refactored the reusable code in …

Library $package 

---

src/services/LibraryService.ts
src/services/MeasureService.ts
src/util/errorUtils.ts
src/util/validationUtils.ts
test/services/LibraryService.test.ts
test/services/MeasureService.test.ts

Updates the OperationOutcome `issue.code` for all thrown OperationOutcomes to be of type `IssueType`.
When an error is thrown from the server, the resulting OperationOutcome will have an `issue.code` that is a valid `IssueType` - see the [code system](https://www.hl7.org/fhir/codesystem-issue-type.html) for more information on what codes are considered valid.
* Updates to `errorUtils.ts` to change the `issue.code`s for the custom error classes. `ResourceNotFoundError` and `NotImplementedError` are pretty straightforward. Since `BadRequestError` is pretty broad, I decided to have the error default to `issue.code` ‘invalid’ (which is the “parent” of invalid codes). Throughout the code, if a more specific code made sense (ex. ‘required’ instead of ‘invalid’ if the request is missing a …

Update OperationOutcome issue codes

---

.env.example
.env.test
.gitignore
package-lock.json
package.json
scripts/dbSetup.ts
src/services/LibraryService.ts
src/services/MeasureService.ts
src/types/node-fhir-server-core.d.ts
src/util/bundleUtils.ts
test/services/MeasureService.test.ts
test/setup.ts
test/util/bundleUtils.test.ts

~Depends on https://github.com/projecttacoma/fqm-execution/pull/186 since it uses the newly-exported ValueSetResolver class with the updated VSAC URL~
~For this to be merged, a new patch version with the linked changes will be released and brought into this code as a dependency.~
This PR includes changes worked on at the January '23 connectathon. Mainly, support for using the VSAC FHIR API during measure packaging, which is useful for the end-to-end workflow demonstration of knowledge repository queries all the way through data submission and measure evaluation.
Besides that, some various QOL updates are included here, such as typescript updates for a custom capability statement and fixes to the period start/end of data requirements to make them not required.
* When using the …

ValueSets and spec updates

---

src/config/capabilityStatementResources.json
src/config/serverConfig.ts
src/types/node-fhir-server-core.d.ts

Adds a custom capability statement of kind “instance” that covers the current capabilities of the measure repository service. It is accessible via the `/metadata` endpoint.
Creates a custom capability statement that reflects the current state of the measure repository service, specifically in regard to the requirements for a Shareable Measure Repository and Publishable Measure Repository. Note the use of the kind “instance,” which requires an implementation to be present and describes its capabilities. Whereas the [Publishable M.R.’s capability statement](https://build.fhir.org/ig/HL7/cqf-measures/CapabilityStatement-publishable-measure-repository.json.html) imports the capability statement for the Shareable M.R., this instance capability statement does not (this is something we can …

Add custom capability statement

---

src/services/LibraryService.ts
src/services/MeasureService.ts
src/util/validationUtils.ts
test/services/LibraryService.test.ts
test/services/MeasureService.test.ts

Adds stricter checking for overlapping id fields. For both `$package` and `$data-requirements`, id can be given as part of the path itself, as in this path parameter: `4_0_1/Measure/:id/$data-requirements`, or the id may be passed as a query parameter (GET) or part of a FHIR parameters object used in a POST. If the id is in both the path and one of these other parameters, the server should throw a 400 bad request error.
Throws 400 bad request for redundant id input, even if the value of the id parameter is the same.
- Updates parameter checking in `package` function for `LibraryService` and `MeasureService`. This function is used for parameter checking in both the `$package` and `$data-requirements` operations. Uses `req.params.id` to determine whether the path parameter is used (Note: …

Error for path parameter w/ query or fhir param

---

README.md
package-lock.json
package.json
scripts/dbSetup.ts
src/config/capabilityStatementResources.json
src/config/serverConfig.ts
src/db/dbOperations.ts
src/index.ts
src/services/LibraryService.ts
src/services/MeasureService.ts
src/util/inputUtils.ts
test/services/LibraryService.test.ts
test/services/MeasureService.test.ts
test/util/inputUtils.test.ts

Exposes the `$submit` operation, which POSTs a new artifact in draft status.
See [this portion of the spec](https://build.fhir.org/ig/HL7/cqf-measures/measure-repository-service.html#submit) for a brief description of the operation. Since the description is not detailed (and no OperationDefinition exists for this operation), we make the following assumptions:
* This operation is supported for both Measures and Libraries
* The operation is defined as a `POST` to `/(Library|Measure)/$submit` or `/(Library|Measure)/[id]/$submit`. Although the spec says that this can be a `PUT`, operations that involve state changes must be invoked by a POST. Therefore, we may not be able to use `PUT` for such an operation (and it is not exposed as an allowable option in node-fhir-server-core when setting up …

Expose $submit operation

---

src/services/LibraryService.ts
src/services/MeasureService.ts

Added check for `content-type` header to the `$data-requirements` function.
Before, we didn't check that the `content-type` header for data-requirements POST requests was `application/json+fhir`, so when the `content-type` header didn't exist, we got the following error message: "Must provide identifying information via either id, url, or identifier parameters". Adding this check makes sure that the user receives the error pertaining to the missing header.
- `LibraryService.ts` - added check that ensures POST requests have `content-type` headers for application json + fhir (same as in the `$package` operation).
- `MeasureService.ts` - added check that ensures POST requests have `content-type` headers for application json + fhir (same as in the `$package` operation).
- `npm run check`
- …

Added content-type header check to data-requirements operation

---

README.md
src/requestSchemas.ts
test/services/LibraryService.test.ts
test/services/MeasureService.test.ts

Section [10.2.1.5.2.1](https://build.fhir.org/ig/HL7/cqf-measures/measure-repository-service.html#core-searches) of the measure repository spec states that for searches, `version` “can appear only in combination with a url search.” This PR requires that url be supplied alongside a version when a version is specified in a Measure/Library search.
When the client performs a `search` with a version and not a url, a `BadRequest` error is thrown explaining that a url must be supplied alongside the version.
* New function in `requestSchemas.ts` that throws a `BadRequest` error if a version is supplied for `search` without a url
* New unit tests in `LibraryService` and `MeasureService` to ensure a 400 error gets thrown when the search query contains version without a url
* Updated test in …

Ensure url specified when version specified for search

---

backend/README.md
backend/scripts/dbSetup.ts
backend/src/config/capabilityStatementResources.json
backend/src/config/serverConfig.ts
backend/src/db/dbOperations.ts
backend/src/services/LibraryService.ts
backend/src/services/MeasureService.ts
backend/test/services/LibraryService.test.ts
backend/test/services/MeasureService.test.ts
backend/test/utils.ts

Because of developments in a decent CRMI call, we want to move away from implementing a $submit operation on the backend and simply allow the measure repository service to support PUT/POST of a new resource (Library or Measure).
The measure repository service now supports PUT/POST of a new resource, where the former uses the ID provided by the requester, and the latter generates a new server ID. This functionality is implemented through `create` and `update` which are already defined in `src/types/service.ts`. This functionality is similar to that in [deqm-test-server](https://github.com/projecttacoma/deqm-test-server).
- `backend/README.md` - Removed $submit info, added create and update info.
- `backend/src/config/capabilityStatementResources.json` - removed submit operation.
- …

Change submit to create and update 

---

backend/src/app.ts
backend/src/index.ts
backend/src/services/BaseService.ts
backend/src/util/baseUtils.ts
backend/test/services/BaseService.test.ts

This PR allows the measure-repository-service to accept artifacts (Libraries and Measure resources only) as transaction bundles. 
Creates the `/:base_version/` endpoint (`/4_0_1/`) for POST requests where the body of the request includes a transaction Bundle of entries that SHALL include a resource (Measure or Library) and request (PUT or POST). 
- `backend/src/index.ts` - `/:base_version/` transaction upload endpoint.
- `backend/src/services/BaseService.ts` - new file to hold all the functions associated with uploading a transaction bundle.
- `backend/src/util/baseUtils.ts` - new file to hold `replaceReferences()`. Let me know if this is unnecessary or if any other functions from `BaseService.ts` should reside here instead. Also includes the `DetailedEntry` type.
- …

Transaction bundle upload

---

frontend/package.json
frontend/pages/[resourceType]/[id].tsx
frontend/styles/globals.css
package-lock.json

Adds a tab to the resource page for the narrative if it exists.
Shows the narrative by pulling the HTML from the narrative right into the view.
New dependency `html-react-parser` to parse HTML string into react components. In `[id].tsx` add the tab and display of narrative. `global.css` add some override of default `th` elements to make it look better.
Load up resources into measure repository. In ecqm-content-r4-2021 the Library FHIR-ModelInfo has a narrative (i.e. `text`), ensure it shows up in the page for the resource. For other resources that do not have the `text` narrative field, ensure the "Narrative" tab does not appear.

Added view of resource narrative if it exists on resources

---

app/src/pages/[resourceType]/[id].tsx

Renders ELM for selected Library resource
Users can now see the rendered ELM for a selected Library resource upon clicking the ELM tab.
`app/src/pages/[resourceType]/[id].tsx` - I enabled the ELM tab so that users can actually click on it when it appears. I added a new Prism component in the ELM tab and make the ELM tab appear/disappear whenever appropriate.
`npm run check:all`
`npm run start:all`
Navigate to http://localhost:3001/ and select both Measure and Library packages. Check that the ELM tab appears whenever the CQL tab appears, and likewise disappears if the CQL tab isn't present. The ELM tab should not appear for any Measures. Additionally, check that the ELM tab is enabled whenever it appears on the screen and that it appropriately renders ELM whenever it is selected by the …

Renders ELM for selected Library resource

---

app/src/pages/[resourceType]/[id].tsx
app/src/pages/api/trpc/[trpc].ts
app/src/pages/authoring/[resourceType]/[id].tsx
app/src/pages/authoring/index.tsx
app/src/server/trpc/routers/draft.ts
app/src/server/trpc/routers/service.ts
app/src/util/modifyResourceFields.ts

This PR allows the user to pull an existing artifact (Measure or Library) from the measure repository service and clone it with a "draft" status instead of "active" status. This adds this new cloned artifact to the local database.
Before, the user could only create new artifacts from scratch and add it to the local database. Now the user can do so using an existing artifact on the measure repository service. The user can do this in the application in one of two ways: navigate to an existing artifact and click "Clone to Draft Artifact" OR go to the authoring page and under "Start From Existing Measure" the user can select a resource to clone.
- `app/src/pages/[resourceType]/[id].tsx` - new button on a specified measure repository service resource page to clone the artifact to a draft.
- …

Draft existing artifacts

---

app/src/components/ResourceCards.tsx
app/src/components/ResourceInfoCard.tsx
app/src/pages/[resourceType].tsx
app/src/pages/[resourceType]/search-result.tsx
app/src/pages/authoring/[resourceType]/index.tsx
app/src/server/trpc/routers/draft.ts
app/src/util/resourceCardUtils.ts

Builds out the `/authoring/[resourceType].tsx` page, allowing the user to view draft artifacts as cards that route to the editing page.
The user can now view resources cards of the available draft artifacts that are stored in the mongo database, which contain identifying fields like `url` and `identifier`. To do so, from authoring “mode,” select a resource type. Then, the contents of each draft resource should be rendered as a resource card. Each resource card also contains an edit button that routes to the editing page so that the user can edit the selected resource.
* `app/src/pages/authoring/[resourceType]/index.tsx` —> builds out the `[resourceType]` page by getting the resources using a `trpc` query, mapping the resources to the resource card content (`id`, `identifier`, etc.), and …

Render draft artifacts in authoring mode

---

app/src/components/ArtifactFieldInput.tsx
app/src/pages/authoring/[resourceType]/[id].tsx
app/src/server/db/dbOperations.ts
app/src/server/trpc/routers/draft.ts
app/src/util/resourceCardUtils.ts

This PR allows the user to be able to edit/modify existing draft artifacts and save those edits to the local database.
When a user creates or selects a draft artifact, a list of text inputs for the following fields are displayed next to the JSON of the artifact: `url`, `identifier`, `name`, `title`, and `description`. If any of these fields already exists on the artifact, then the text inputs will be populated with their current values. The user can edit or delete the content of these fields, but artifact in the local database will only be updated when the user clicks "Submit". 
- `app/src/pages/authoring/[resourceType]/[id].tsx` - Add inputs for `name`, `title`, and `description`, modified the `parseUpdate` function to return additions and deletions that we want to update the artifact …

Edit draft artifacts

---

app/src/components/DataRequirements.tsx
app/src/pages/[resourceType]/[id].tsx

This PR allows users to toggle between two different views for the data requirements of a specified resource: The raw version of the data requirements and a readable version of the data requirements array.
The data requirements panel now populates with a `Segment Controller` mantine component at the top of the panel where the user can manually toggle between two different displays of the data requirements. The panel should always initially start out on the raw data requirements view. If the user manually selects the " readable data requirements" view they will then see a series of data requirement cards. Each card has an icon in the upper right hand corner the user can click to expand/constrict the card. Each card should display specific information of one element from the data …

Make Data Requirements Human Readable

---

app/src/components/DependencyCards.tsx
app/src/pages/[resourceType]/[id].tsx

The user can now render the dependencies/relatedArtifacts of a resource!
By clicking the "Get Data Requirements" button for a resource, a new `"Dependencies" mantine tab` will pop up. Each of the resource's dependencies and their respective fields  should display in a card component. If the dependency is another library/measure resource then a `SquareArrowRight icon` should appear on the card that, when clicked, links to that resource's own page. 
`app/src/components/DependencyCards.tsx` —> Extracts the different fields and properties of each of the dependencies of a resource and displays them in a card component
` ScrollArea` —> The scrollArea component allows users to scroll through a resource's dependencies and continue to see the top of the page
`Link `--> The user can click the …

Render Resource Dependencies

---

app/package.json
app/src/pages/review/[resourceType]/[id].tsx
package-lock.json
package.json

This PR allows users to add an artifact comment to a **draft** resource.
On the review page for an artifact, users will be greeted with a `use-form mantine` component in the `add comment` tab panel. Via the form, users can enter the following information: The comment, their name, [the comment type](https://build.fhir.org/ig/HL7/cqf-measures/CodeSystem-artifact-comment-type.html), and whether they would like to include the date or not. The exact current date/time is what will be added to the artifact comment if the user chooses to include the date. Amongst these 4 parameters, only the comment type and the actual comment are needed in order to submit the form. Upon submitting the form, the submit button should show a `loader icon` for 1 millisecond, the form properties should clear …

Add Artifact comments to a draft resource

---

app/src/pages/[resourceType]/[id].tsx
app/src/pages/authoring/[resourceType]/[id].tsx
package-lock.json
service/src/db/dbOperations.ts
service/src/services/LibraryService.ts
service/src/services/MeasureService.ts
service/src/types/service-types.ts
service/test/services/LibraryService.test.ts
service/test/services/MeasureService.test.ts

When the `$data-requirements` for a specific artifact and set of parameters are calculated, they are then cached in the mongo database that stores active artifacts so that these Library data requirements resources can be accessed again without having to rerun calculation. 
Before, whenever the user requested the data-requirements for an artifact (either with the `$data-requirements` endpoint or in the UI, the data-requirements calculation was done each time. In order to improve performance in our application, we now cache these Library resources in the Library collection in the published repository service.
We talked about different strategies for how to cache data-requirements and where but ultimately settled on the following (for now):
1. When the user navigates to an artifact's page in …

Cache data-requirements

---

app/src/components/DependencyCards.tsx
app/src/pages/[resourceType]/[id].tsx
service/scripts/dbSetup.ts

Adds an `id` to resources uploaded to the measure repository service via the `db:loadBundle` script. Adds handling for dependency card rendering.
The `db:loadBundle` script does not check for the presence of an id on the uploaded artifacts, and so artifacts can be uploaded to the server that do not have an `id`. This causes apps that consume the measure repository endpoints (i.e. `[id]/$package` in `fqm-testify`) to throw errors.
The script now adds a new `uuid` to a resource if an `id` is not pre-defined on the resource prior to upload.
Additionally, filters out related artifacts without the `.resource` field. This will filter out resources that use `.url` instead.
* App/src/pages/[resourceType]/[id].tsx —> adds related artifact filtering
* Service/scripts/dbSetup.ts —> adds uuid to …

Assign ID to resources during bundle upload

---

.github/workflows/ci.yml
app/README.md
app/package.json
app/src/components/SidebarButtonList.tsx
package-lock.json
service/README.md

Updates `next` to 14.0.0 and fixes console warnings that appear due to invalid `href` formatting.
The application **no longer** produces the following console warnings due to routing:
* `workflows/ci.yml` - Upgrade the node version used
* `app/README.md` and `service/README.md` - Upgrade the minimum node version used. (I believe 18 should be the minimum node version since that is required by `next`, and v16 has reached EOL.)
* `app/package.json` - update to `next` 14.0
* `src/components/SidebarButtonList.tsx` - Remote the default route prefix of `/`. 
* The routing warnings that we are seeing are concerned with the `/Measure` and `/Library` routes, which display the resources of the given resource type. They are accessed from the sidebar button list. The Link that gets created for routing …

Upgrade next, Fix button routing

---

service/README.md
service/src/config/capabilityStatementResources.json
service/src/config/serverConfig.ts
service/src/requestSchemas.ts
service/src/services/LibraryService.ts
service/src/services/MeasureService.ts
service/src/util/bundleUtils.ts
service/src/util/inputUtils.ts
service/test/services/LibraryService.test.ts
service/test/services/MeasureService.test.ts

The [published version of the measure repository service](http://hl7.org/fhir/us/cqfmeasures/OperationDefinition/cqfm-package) now specifies `$cqfm.package` as the endpoint for the package operation. This PR changes instances of `$package` with `$cqfm.package`.
No new features. Changes the package endpoint from `$package` to `$cqfm.package`. Also updates our schema instances, which impacts which parameters throw errors when caught being used without support from the server.
* README updates
* `capabilityStatementResources.json` - update OperationDefinition link for the package operation
* `serverConfig.ts` - update operation endpoint and reference
* `requestSchemas.ts` - Made updates to unsupported package args and general package args schema based on changes to the spec.
* Updates to …

Update package endpoint to cqfm.package

---

README.md
app/README.md
app/src/components/ReleaseModal.tsx
app/src/pages/index.tsx
service/README.md
service/src/requestSchemas.ts

Updates the landing page with a link to the top level README and the location of the service endpoints.
Appropriate links and description on the landing page
Updates to `index.tsx`
`npm run check:all`
`npm run start:all`
View landing page at http://localhost:3001/ and check description and links.

Update landing page with README link and service location

---

service/README.md
service/directory-upload.sh
service/scripts/dbSetup.ts
service/src/services/BaseService.ts
service/src/services/LibraryService.ts
service/src/services/MeasureService.ts
service/src/util/baseUtils.ts

Adds support for directory bundle upload via both the `db:loadBundle` npm script as well as a new batch script.
The user now has the ability to upload entire directories of bundles to the measure repository rather than needing to run a command on each individual JSON file.
The existing `db:loadBundle` script can be used for directory upload and supports nested directories (one level deep). The script detects whether the input path refers to a file or directory. The new bash script also supports nested directories and applies a transaction bundle upload via a curl command to each of the bundles contained in the directory.
* `service/scripts/dbSetup.ts` - update script to check whether the input path is a directory, and loop over all JSON files accordingly
* `service/directory-upload.sh` - …

Add support for directory upload

---

app/src/server/trpc/routers/service.ts
service/README.md
service/src/db/dbOperations.ts
service/src/requestSchemas.ts
service/src/services/LibraryService.ts
service/src/services/MeasureService.ts
service/src/util/bundleUtils.ts

This PR adds the `_summary` search parameter (specified in the HL7 FHIR docs [here](https://www.hl7.org/fhir/search.html#_summary)) to the Library and Measure search capabilities. Adding this allows our `getArtifactCounts` trpc procedure on the frontend to get the number of artifacts without sending a request that gets all of the artifacts.
Before, it took awhile for the frontend application to load the number of Measure and Library artifacts. This was due to how our `getArtifactCounts` trpc procedure was written- a GET request was sent to get all of the Measures and Libraries and then `.total` on the searchset bundle was returned. Now, `getArtifactCounts` sends requests to `/Measure?_summary=count` and `/Library?_summary=count` so that searchsets excluding all of the entries are …

Added _summary search param for artifact count optimization

---

service/scripts/dbSetup.ts
service/src/services/BaseService.ts
service/src/util/baseUtils.ts

Previously, we had only implemented the `isOwned` child artifact functionality when bundles were uploaded using the `dbSetup.ts` script (`npm run db:loadBundle`). Now that we have the `./directory-upload.sh` script, want want to make sure that the `isOwned` extension gets added when transaction bundles are uploaded.
The same thing that is done for adding the `isOwned` extension on the `relatedArtifacts` of Measures is now done for transaction bundle uploads as well as the `dbSetup.ts` script.
Note: there is more code that we can probably consolidate/make more reusable but I tried to keep it to the scope of the `isOwned` extension so that we can have this functionality for the Connectathon.
- `dbSetup.ts` - pulled out `isOwned` extension code and replaced it with a function call …

Add isOwned extension functionality to txn bundle upload

---

app/src/components/ReleaseModal.tsx
app/src/server/db/mongodb.ts
app/src/server/trpc/routers/service.ts
service/scripts/dbSetup.ts
service/src/db/dbOperations.ts
service/src/services/LibraryService.ts
service/src/services/MeasureService.ts

Enforced unique combination of url and version for both draft artifacts and measure repository artifacts. Updates some error handling to show useful error information to the user.
If a user attempts to create a resource (new or update or through operations or http PUT/POST) that has a combined url/version that conflicts with an existing combined url/version, they will receive an error indicating that the action failed because of a duplicate key (and will show the duplicate keys in question).
dbSetup.ts - creates a unique url/version index for the measure-repository collections
mongodb.ts - creates a unique url/version index for the draft-repository collections
service.ts - passes an error through if a 500 response is received from the server
ReleaseModal.tsx - on release, prioritizes …

Enforce unique combined url and version

---

app/src/pages/[resourceType]/[id].tsx
app/src/pages/authoring/[resourceType]/[id].tsx
app/src/pages/authoring/index.tsx
app/src/server/trpc/routers/service.ts
service/scripts/dbSetup.ts
service/src/services/BaseService.ts
service/src/util/baseUtils.ts

Adds logic for adding the isOwned extension onto a library during upload if that library is a child artifact, and uses the isOwned extension to disable release and drafting operations for the child.
- Child libraries have an isOwned extension.
- Child artifacts may not be drafted or released
- Changes in `[id].tsx` for both the repository and authoring side to disable draft and release respectively
- Changes to `index.tsx` to have a more informative select placeholder and to `service.ts` to populate the select with data that has child artifacts disabled
- 'baseUtils.ts` `addIsOwnedExtension` returns the url for the reference and `addLibraryIsOwned` function creates an isOwned extension on the passed entry resource if its url is in the passed list of ownedUrls
- `BaseService.ts` and …

Disable child operations

---

app/src/server/trpc/routers/service.ts

Adds version to the label of an artifact so it's not just the name or id. This prevents multiple artifacts of the same name but with different versions appearing in the dropdown for drafting measures:
None
- `service.ts` - add version to the artifact label
- `npm run check:all`
- `npm run start:all`
- Make sure everything looks good!

Add version to the artifact name/id in the dropdown

---

app/src/components/ReleaseModal.tsx
app/src/server/trpc/routers/service.ts

Child resources are batched with their parent for release.
The front end acts the same with some minor tweaks to notifications. Under the hood, the parent and child artifacts are released using a transaction bundle in order to ensure they are batched.
- ReleaseModal - releaseChild mutation is removed, transaction bundles response expected to be a 200, a notification is shown and a resource deleted for every released resource in the `deletable` list
- service.ts - construct a transaction bundle, and create a toDelete structure with the parent data, then iterate through the children to add to the transaction bundle entries and the toDelete structure. Send transaction bundle and use response to send new location and deletable resource information to the ReleaseModal
- `npm run check:all`
- …

Batch release

---

app/src/pages/[resourceType].tsx
app/src/server/trpc/routers/service.ts
service/README.md
service/src/db/dbOperations.ts
service/src/requestSchemas.ts
service/src/services/LibraryService.ts
service/src/services/MeasureService.ts
service/src/util/queryUtils.ts
service/test/services/LibraryService.test.ts
service/test/services/MeasureService.test.ts

This PR implements the `_elements` search parameter (https://www.hl7.org/fhir/search.html#_elements) in Measure and Library search in order to speed up rendering of the list of artifacts in the frontend.
When navigating to the Measure and Library tabs in the measure repository service app, it no longer takes time for it to load because it is now only fetching the necessary information we need from the server rather than the entirety of all of the artifacts.
- `app/src/pages/[resourceType].tsx` - add `_elements` parameter with the elements that we want in order to speed up this fetch
- `app/src/server/trpc/routers/service.ts` - add `_elements` parameter with the elements that we want in order to speed up this fetch
- `service/src/db/dbOperations.ts` - adds a function for getting resources …

Add _elements search param

---

app/src/server/trpc/routers/service.ts
app/src/util/modifyResourceFields.ts

Increment draft version up to 10 times based on any versions that already exist in the draft database.
Creating a draft of a repository artifact multiple times succeeds and increments the version as expected up to a limit.
modifyResourceFields.ts - changes to `modifyResourceToDraft` function to check the draft database for existing versions of the proposed increment and to continue incrementing until an acceptable version is found or the count limit (10) is reached.
service.ts - changes to await the newly async `modifyResourceToDraft` function
Note: I considered doing a different error message if we hit the count limit, but I think the theory that we're working on is that we will never need this many drafts of the same resource at the same time. I think if we think a user will ever …

Increment draft version

---

README.md
app/.env.example
docker-compose.example.yml
docker-compose.yml
service/.env.example

Update docker setup to create replica set in containers. Update documentation and environment examples for local mongodb replica set.
Docker starts up using a replica set (and user can do local development with a replica set) allowing the use of certain db features (like transactions).
- README has instructions for local replica set changes.
- Environment variables are updated to reflect replica set connection. 
- docker-compose and the docker-compose example are updated to set up replica set.
- Follow the README to set up the local replica set.
- Build and restart the app.
- Verify basic application function by creating draft measures and releasing them.
- Stop your local mongodb and application and run `docker compose up --build` instead
- Verify basic application function by creating …

replica set for docker

---

app/src/pages/[resourceType]/[id].tsx
app/src/pages/authoring/index.tsx
app/src/server/db/dbOperations.ts
app/src/server/trpc/routers/service.ts

Parent and child artifacts are batched for the draft action.
Note: the mongod transaction functionality requires us to be running mongod using replica sets rather than as standalone. Trying to run on a standalone configuration will cause: `MongoError: Transaction numbers are only allowed on a replica set member or mongos`
For this PR, make sure you've followed directions added from the previous replica set PR so that your local configuration is using replica sets.
Parent and child artifacts are drafted in batch, so that if one fails, the other fails as well. This is implemented as a database transaction.
- dbOperations adds `batchCreateDraft` which uses a transaction to do multiple inserts
- service.ts removes the `draftChild` procedure and bundles parent and child together for insertion …

batch draft

---

app/src/components/ReleaseModal.tsx
app/src/server/trpc/routers/service.ts
app/src/util/modifyResourceFields.ts
app/src/util/serviceUtils.ts
service/scripts/dbSetup.ts

We recently noticed an error that we made in our release logic- `getChildren` pulls child artifacts from the measure repository service; however, for the "release" functionality of the app, we should be pulling the children from the draft repository instead.
New function called `getDraftChildren` in `serviceUtils.ts` gets child artifacts from the draft repository when release is being called on an artifact.
- `app/src/util/serviceUtils.ts` - adds `getDraftChildren` function.
- `app/src/util/modifyResourceFields.ts` - `modifyResourceToDraft` function properly increments the version on the relatedArtifact url rather than assigning it to the parent artifact's version.
- `app/src/server/trpc/routers/service.ts` - `releaseParent` trpc procedure now properly calls `getDraftChildren` to get the …

Fix recursion

---

app/src/components/ResourceInfoCard.tsx
app/src/server/db/dbOperations.ts
app/src/server/trpc/routers/draft.ts
app/src/util/modifyResourceFields.ts
app/src/util/resourceCardUtils.ts
app/src/util/types/fhir.ts

This PR continues our work of ensuring that child artifacts in the measure-repository do not have a lifecycle outside of their parent artifact. This PR prevents child artifacts from being deleted from the `draft-repository` and implements recursive deletion of a parent artifact and all of its children in a batch transaction.
- The "delete" button is disabled in the `draft-repository` (authoring side of the app) for artifacts that are child artifacts (meaning they have the `isOwned` extension). 
- Artifact deletion of the `draft-repository` is now batched so that the artifact and any of its child artifacts are also deleted.
- `app/src/components/ResourceInfoCard.tsx` - `deleteParent` trpc procedure is now used instead of `deleteDraft`, delete button is now disabled for child artifacts
- …

Child artifact delete

---

docker-compose.example.yml

This PR adds a comment to the `docker-compose.example.yml` file to reflect the change that we had to make in the `docker-compose.yml` in abacus-dev in order to get replicaSet functionality to work on a linux platform.
- n/a
- `docker-compose.example.yml` - adds comment, looks like prettier was applied too
- Make sure abacus-dev.mitre.org/mrs works as intended 
- Make sure this setup makes sense for now. Note that Lauren made a backlog task for looking into this further after our discussion.

Add comment about changing hoster.docker.internal for linux systems

---

app/src/components/ArtifactComments.tsx

Remove functionality that allows the user to change the date format on review comments.
Review comment date is not clickable and stays in the same format. This feature does not seem to have a lot of utility. Removing it fixes an issue with date displays where a review comment card may show the date of another review comment rather than its own. To reproduce this issue on the main branch:
- Add multiple review comments with dates to a draft artifact, taking note of their correct timestamps
- Add a review comment on the add tab
- Immediately switch over to the view tab
- Some review comments will have incorrect timestamps
- Timestamps are fixed with reload
Remove hover, color change, click response, and date formatter, replaced with simple date display.
- 'npm run check:all`
- Run with `npm …

Pull out date change code

---

service/README.md
service/src/config/capabilityStatementResources.json
service/src/config/serverConfig.ts
service/src/db/dbOperations.ts
service/src/requestSchemas.ts
service/src/services/LibraryService.ts
service/src/services/MeasureService.ts
service/src/util/inputUtils.ts
service/src/util/serviceUtils.ts
service/test/services/LibraryService.test.ts
service/test/services/MeasureService.test.ts

This PR exposes the $clone operation as an endpoint on the server. This functionality is defined in the CRMI IG [here](https://build.fhir.org/ig/HL7/crmi-ig/OperationDefinition-crmi-clone.html).
The current OperationDefinition of the clone operation does not include `url` as an input parameter. This is an error and is being tracked in [this](https://jira.hl7.org/browse/FHIR-46385) Jira issue by Paul. Additionally, the spec needs to detail how child artifacts will be handled for clone. For now, I made the decision to simply add `-clone` to the end of the child artifact url when its parent is cloned. This approach made the most sense to me since there is no current guidance for it and the url cannot stay the same but I am open to suggestions!
The user can now clone a Measure or Library …

Expose clone operation

---

README.md
app/src/pages/[resourceType]/[id].tsx
app/src/server/trpc/routers/service.ts
app/src/util/authoringFixtures.ts
app/src/util/types/fhir.ts
service/scripts/dbSetup.ts
service/src/config/capabilityStatementResources.json
service/src/db/dbOperations.ts
service/src/services/BaseService.ts
service/src/services/LibraryService.ts
service/src/services/MeasureService.ts
service/src/types/service-types.ts
service/src/types/service.ts
service/src/util/baseUtils.ts
service/src/util/bundleUtils.ts
service/src/util/inputUtils.ts
service/test/services/LibraryService.test.ts
service/test/services/MeasureService.test.ts
service/test/util/bundleUtils.test.ts
service/test/util/serviceUtils.test.ts
service/test/utils.ts

This PR updates the typing of Libraries and Measures by using (when possible) [CRMIShareableMeasure](https://hl7.org/fhir/uv/crmi/StructureDefinition-crmi-shareablemeasure.html) and [CRMIShareableLibrary](https://hl7.org/fhir/uv/crmi/StructureDefinition-crmi-shareablelibrary.html) type definitions. 
The CRMIShareableMeasure and CRMIShareableLibrary definitions only vary slightly from that of fhir4.Measure and fhir4.Library- they are both extended from them but also require `version`, `url`, `title`, `status` and `description`. 
- A lot of changing `fhir4.FhirResource` to `fhir4.Measure` and `fhir4.Library` to `CRMIShareableMeasure` and `CRMIShareableLibrary`. 
- A lot of making sure test fixtures have additional attributes (`url`, `version`, `title`, `description`)
- Deleting some no …

Transition to use CRMI definitions for Measure and Library

---

service/README.md
service/src/config/capabilityStatementResources.json
service/src/config/serverConfig.ts
service/src/db/dbOperations.ts
service/src/requestSchemas.ts
service/src/services/LibraryService.ts
service/src/services/MeasureService.ts
service/src/util/inputUtils.ts
service/src/util/serviceUtils.ts
service/test/services/LibraryService.test.ts
service/test/services/MeasureService.test.ts

This PR exposes the $approve operation as an endpoint on the server. This functionality is defined in the CRMI IG [here](https://hl7.org/fhir/uv/crmi/OperationDefinition-crmi-approve.html).
The user can now approve a Measure or Library artifact and any resources it is composed of regardless of status by sending a GET or POST request to `Measure/$approve`, `Measure/:id/$approve`, `Library/$approve` and `Library/:id/$approve`. This operation takes three optional parameters: `approvalDate`, `artifactAssessmentType`, and `artifactAssessmentSummary`. If `artifactAssessmentType` and `artifactAssessmentSummary` are both provided, then a [cqf-artifactComment](https://hl7.org/fhir/extensions/5.1.0/StructureDefinition-cqf-artifactComment.html) extension will be added to the artifact and any of its …

Expose  operation

---

service/README.md
service/src/config/capabilityStatementResources.json
service/src/config/serverConfig.ts
service/src/requestSchemas.ts
service/src/services/LibraryService.ts
service/src/services/MeasureService.ts
service/test/services/LibraryService.test.ts
service/test/services/MeasureService.test.ts

Implements the `$review` endpoint in the server according to the [CRMI IG definition](https://hl7.org/fhir/uv/crmi/OperationDefinition-crmi-review.html).
For all details, this functionality is essentially the same as `$approve` with the exception of the `approvalDate` parameter, which becomes the `reviewDate`, and instead of setting the `approvalDate` field on the artifact, it sets the `lastReviewDate` field.
See https://github.com/projecttacoma/measure-repository/pull/106
Use the testing guidance in https://github.com/projecttacoma/measure-repository/pull/106, including Insomnia requests, but change all `$approve` to `$review` and all `approvalDate` parameters to `reviewDate`.

Expose review

---

service/src/db/dbOperations.ts
service/test/services/BaseService.test.ts
service/test/services/LibraryService.test.ts
service/test/services/MeasureService.test.ts
service/test/util/bundleUtils.test.ts
service/test/util/serviceUtils.test.ts
service/test/utils.ts

Currently when a database change is made that would cause a duplicate `url` and `id` to occur, the response from the server is 500 from mongo enforcing the restraint. This work catches the specific mongo errors responds with a 400 Bad Request `invalid` response explaining the issue. 
All DB operations that make changes will catch the duplicate key errors from mongo and throw a BadRequestError that will result in a 400 response.
Adds collection index creation to the test db setup functions and fixes many async issues with the unit tests.
`dbOperations.ts` - Added a helper function to convert a caught error to a BadRequestError if it happens to be the mongo duplicate key error.
`tests/utils.ts` - Added index creation to `setupTestDatabase`.
Unit Tests - Fixes to many of the test database …

Handle duplicate key errors from mongo and return Bad Request errors

---

service/README.md
service/scripts/dbSetup.ts
service/src/config/capabilityStatementResources.json
service/src/config/serverConfig.ts
service/src/requestSchemas.ts
service/src/services/LibraryService.ts
service/src/services/MeasureService.ts
service/test/services/LibraryService.test.ts
service/test/services/MeasureService.test.ts
service/test/utils.ts

Implements the `$release` endpoint in the server according to the [CRMI IG definition](https://hl7.org/fhir/uv/crmi/OperationDefinition-crmi-release.html).
The user can now release a Measure or Library draft artifact and any resources it is composed of by sending a GET or POST request to `Measure/$release`, `Measure/:id/$release`, `Library/$release` and `Library/:id/$release`. This operation takes three required parameters: `id`, `releaseVersion`, and `versionBehavior`. It updates the artifact and children artifact `date` and `version`. For pieces of the spec that are a unclear, questions have been added to the connectathon document.
- `service/README.md` - add description of `$release`
- `service/scripts/dbSetup.ts` - add check for publishable environment before coercing to active
- …

release implementation

---

service/README.md
service/src/db/dbOperations.ts
service/src/services/LibraryService.ts
service/src/services/MeasureService.ts

This PR ensures that the Publishable Measure Repository `archive` DELETE and the Authoring Measure Repository `withdraw` DELETE interactions include handling of child artifacts. Additionally, it includes handling of child artifacts for the Publishable Measure Repository `retire` UPDATE interaction.
- When sending a DELETE request (withdraw) to an artifact with status `draft`, it now also deletes any resources it is composed of, recursively.
- When sending a DELETE request (archive) to an artifact with status `retired`, it now also deletes any resources it is composed of, recursively.
- When sending an UPDATE request (retire) to an artifact with status `active` where the only update is the date changing and the status changing to `retired`, it now also updates any resources it is composed …

Child artifact deletion and retire

---

app/src/components/ResourceInfoCard.tsx
app/src/components/SearchComponent.tsx
app/src/pages/[resourceType]/[id].tsx
app/src/pages/_app.tsx
app/src/pages/authoring/[resourceType]/[id].tsx
app/src/pages/authoring/[resourceType]/index.tsx
app/src/pages/authoring/index.tsx
app/src/pages/index.tsx
app/src/server/trpc/routers/service.ts
service/src/config/publishableCapabilityStatementResources.json
service/src/config/serverConfig.ts

Updates capability statement from server to reflect publishable/authoring environment. Updates frontend application to use capability statement to hide authoring capabilities if the server is in publishable mode.
Server provides publishable capability statement at `/metadata` endpoint if the server is in publishable mode (i.e. AUTHORING env variable is false). If the server is in publishable mode, the frontend with show a different capability statement on the main page, and authoring operations and draft measure interactions will be disabled.
- Server: adds `publishableCapabilityStatementResources.json` and updates `serverConfig.ts` to share publishable capability statement according to environment variable.
- Update search to show only status active (This seems to be the intention of our …

Pub auth frontend
